-- ============================================================
-- Manaqeesh W Nar — products migration
-- Run this in: Supabase Dashboard → SQL Editor → New query → Run
-- Safe to re-run (uses IF NOT EXISTS / ON CONFLICT DO NOTHING)
-- ============================================================

-- Step 1: Add sizes + emoji columns
ALTER TABLE products
  ADD COLUMN IF NOT EXISTS sizes JSONB,
  ADD COLUMN IF NOT EXISTS emoji TEXT;

-- Step 2: Unique index for idempotent inserts
CREATE UNIQUE INDEX IF NOT EXISTS products_name_category_uniq
  ON products (name, category);

-- Step 3: Insert 109 products
INSERT INTO products (name, description, price, image_url, category, available, emoji, sizes)
VALUES
  ('شاورما دجاج كلاسيك', NULL, 1.25, NULL, 'شاورما', TRUE, '🥙', '[{"label":"ساندويش","price":1.25},{"label":"عادي","price":2.6},{"label":"سوبر","price":3.2},{"label":"دبل","price":3.85},{"label":"تربل","price":5}]'::jsonb),
  ('شاورما دجاج مع الكريمة والجبنة', NULL, 1.5, NULL, 'شاورما', TRUE, '🥙', '[{"label":"ساندويش","price":1.5},{"label":"عادي","price":3},{"label":"سوبر","price":3.5},{"label":"دبل","price":4},{"label":"تربل","price":5.3}]'::jsonb),
  ('شاورما دجاج مع دبس الرمان والجبنة', NULL, 1.5, NULL, 'شاورما', TRUE, '🥙', '[{"label":"ساندويش","price":1.5},{"label":"عادي","price":3},{"label":"سوبر","price":3.5},{"label":"دبل","price":4},{"label":"تربل","price":5.3}]'::jsonb),
  ('شاورما دجاج بافيلو', NULL, 1.5, NULL, 'شاورما', TRUE, '🌶️', '[{"label":"ساندويش","price":1.5},{"label":"عادي","price":3},{"label":"سوبر","price":3.5},{"label":"دبل","price":4},{"label":"تربل","price":5.3}]'::jsonb),
  ('شاورما دجاج مدخن', NULL, 1.5, NULL, 'شاورما', TRUE, '🥙', '[{"label":"ساندويش","price":1.5},{"label":"عادي","price":3},{"label":"سوبر","price":3.5},{"label":"دبل","price":4},{"label":"تربل","price":5.3}]'::jsonb),
  ('وجبة الشاورما العائلية', '56 قطعة شاورما، 2 صحن بطاطا كبير، 2 لتر بيبسي، مخلل وصوصات', 14, NULL, 'وجبات شاورما', TRUE, '🍱', '[{"label":"كلاسيك","price":14},{"label":"ميكس","price":15}]'::jsonb),
  ('وجبة الشاورما الشبابية', '35 قطعة شاورما، 1 صحن بطاطا كبير، 1 لتر بيبسي، مخلل وصوصات', 9, NULL, 'وجبات شاورما', TRUE, '🍱', '[{"label":"كلاسيك","price":9},{"label":"ميكس","price":10}]'::jsonb),
  ('مارجريتا', 'جبنة موزاريلا + صلصة', 2, NULL, 'بيتزا', TRUE, '🍕', '[{"label":"صغير","price":2},{"label":"وسط","price":2.6},{"label":"كبير","price":4}]'::jsonb),
  ('خضار', 'فليفلة حلوة + فطر + زيتون + جبنة موزاريلا + صلصة', 2.25, NULL, 'بيتزا', TRUE, '🥗', '[{"label":"صغير","price":2.25},{"label":"وسط","price":3.2},{"label":"كبير","price":4.5}]'::jsonb),
  ('ببروني', 'ببروني + جبنة موزاريلا + صلصة', 2.5, NULL, 'بيتزا', TRUE, '🍖', '[{"label":"صغير","price":2.5},{"label":"وسط","price":3.5},{"label":"كبير","price":4.5}]'::jsonb),
  ('تيركي', 'تيركي + جبنة موزاريلا + صلصة', 2.5, NULL, 'بيتزا', TRUE, '🦃', '[{"label":"صغير","price":2.5},{"label":"وسط","price":3.5},{"label":"كبير","price":4.5}]'::jsonb),
  ('فونجي', 'فطر طازج + جبنة موزاريلا + صلصة', 2.5, NULL, 'بيتزا', TRUE, '🍄', '[{"label":"صغير","price":2.5},{"label":"وسط","price":3.2},{"label":"كبير","price":4.5}]'::jsonb),
  ('خضار إيطالية', 'كوسا + باذنجان + فطر + فليفلة + زيتون + طماطم كرزية + موزاريلا', 2.5, NULL, 'بيتزا', TRUE, '🫑', '[{"label":"صغير","price":2.5},{"label":"وسط","price":3.5},{"label":"كبير","price":4.5}]'::jsonb),
  ('هوت دوغ', 'زيتون + هوت دوغ + جبنة موزاريلا + صلصة', 2.5, NULL, 'بيتزا', TRUE, '🌭', '[{"label":"صغير","price":2.5},{"label":"وسط","price":3.5},{"label":"كبير","price":4.5}]'::jsonb),
  ('بيتزا الفصول الأربعة', 'صوص البيتزا + موزاريلا + شيدر + حلوم', 3, NULL, 'بيتزا', TRUE, '🍀', '[{"label":"صغير","price":3},{"label":"وسط","price":4},{"label":"كبير","price":5}]'::jsonb),
  ('دجاج مع خضار', 'دجاج + خضار + جبنة موزاريلا + صلصة', 3, NULL, 'بيتزا', TRUE, '🍗', '[{"label":"صغير","price":3},{"label":"وسط","price":4.5},{"label":"كبير","price":5.5}]'::jsonb),
  ('دجاج باربيكيو', 'دجاج + صلصة باربيكيو + جبنة موزاريلا', 3, NULL, 'بيتزا', TRUE, '🍗', '[{"label":"صغير","price":3},{"label":"وسط","price":4.5},{"label":"كبير","price":5.5}]'::jsonb),
  ('سوبريم', 'ببروني + موزاريلا + صلصة + هوت دوغ + لحمة + خضار', 3, NULL, 'بيتزا', TRUE, '👑', '[{"label":"صغير","price":3},{"label":"وسط","price":4.5},{"label":"كبير","price":5.5}]'::jsonb),
  ('دجاج ألفريدو', 'دجاج + صلصة ألفريدو + فطر', 3, NULL, 'بيتزا', TRUE, '🍗', '[{"label":"صغير","price":3},{"label":"وسط","price":4.5},{"label":"كبير","price":5.5}]'::jsonb),
  ('بيتزا الزنجر', 'زنجر + صوص + فليفلة خضرة + موزاريلا + زيتون', 3, NULL, 'بيتزا', TRUE, '🌶️', '[{"label":"صغير","price":3},{"label":"وسط","price":4.5},{"label":"كبير","price":5.5}]'::jsonb),
  ('بيتزا منقوشة ونار', 'شاورما + صوص + موزاريلا', 3, NULL, 'بيتزا', TRUE, '🔥', '[{"label":"صغير","price":3},{"label":"وسط","price":4.5},{"label":"كبير","price":5.5}]'::jsonb),
  ('بيتزا لحمة', 'صوص + لحمة + خضار', 3, NULL, 'بيتزا', TRUE, '🥩', '[{"label":"صغير","price":3},{"label":"وسط","price":4.5},{"label":"كبير","price":5.5}]'::jsonb),
  ('زعتر', NULL, 0.75, NULL, 'مناقيش', TRUE, '🌿', '[{"label":"عادي","price":0.75},{"label":"كبير","price":1}]'::jsonb),
  ('زعتر مع خضار', NULL, 1, NULL, 'مناقيش', TRUE, '🌿', NULL),
  ('زعتر مع جبنة وخضار', NULL, 1.25, NULL, 'مناقيش', TRUE, '🌿', NULL),
  ('جبنة بيضاء', NULL, 1.15, NULL, 'مناقيش', TRUE, '🧀', '[{"label":"عادي","price":1.15},{"label":"كبير","price":2.35}]'::jsonb),
  ('جبنة بيضاء مع خضار', NULL, 1.15, NULL, 'مناقيش', TRUE, '🧀', NULL),
  ('جبنة حلوم', NULL, 1.15, NULL, 'مناقيش', TRUE, '🧀', '[{"label":"عادي","price":1.15},{"label":"كبير","price":2.35}]'::jsonb),
  ('جبنة حلوم مع خضار', NULL, 1.25, NULL, 'مناقيش', TRUE, '🧀', NULL),
  ('لبنة مع زعتر', NULL, 1.15, NULL, 'مناقيش', TRUE, '🫙', '[{"label":"عادي","price":1.15},{"label":"كبير","price":2.35}]'::jsonb),
  ('لبنة مع خضار', NULL, 1.15, NULL, 'مناقيش', TRUE, '🫙', NULL),
  ('لبنة مع زعتر وخضار', NULL, 1.25, NULL, 'مناقيش', TRUE, '🫙', '[{"label":"عادي","price":1.25},{"label":"كبير","price":2.35}]'::jsonb),
  ('مكس أجبان', NULL, 1.25, NULL, 'مناقيش', TRUE, '🧀', '[{"label":"عادي","price":1.25},{"label":"كبير","price":2.35}]'::jsonb),
  ('أجبان الفصول الأربعة', NULL, 1.35, NULL, 'مناقيش', TRUE, '🧀', '[{"label":"عادي","price":1.35},{"label":"كبير","price":3.2}]'::jsonb),
  ('جبنة كشكوان', NULL, 1.15, NULL, 'مناقيش', TRUE, '🧀', '[{"label":"عادي","price":1.15},{"label":"كبير","price":2.35}]'::jsonb),
  ('جبنة صفراء', NULL, 1.15, NULL, 'مناقيش', TRUE, '🧀', '[{"label":"عادي","price":1.15},{"label":"كبير","price":2.35}]'::jsonb),
  ('كشكوان مع تيركي', NULL, 1.25, NULL, 'مناقيش', TRUE, '🦃', '[{"label":"عادي","price":1.25},{"label":"كبير","price":2.95}]'::jsonb),
  ('كشكوان مع سلامي', NULL, 1.25, NULL, 'مناقيش', TRUE, '🍖', '[{"label":"عادي","price":1.25},{"label":"كبير","price":2.95}]'::jsonb),
  ('كشكوان مع هوت دوغ', NULL, 1.25, NULL, 'مناقيش', TRUE, '🌭', '[{"label":"عادي","price":1.25},{"label":"كبير","price":2.95}]'::jsonb),
  ('كشكوان مع سجق', NULL, 1.25, NULL, 'مناقيش', TRUE, '🌭', '[{"label":"عادي","price":1.25},{"label":"كبير","price":2.95}]'::jsonb),
  ('كشكوان مع بسطرمة', NULL, 1.25, NULL, 'مناقيش', TRUE, '🥩', '[{"label":"عادي","price":1.25},{"label":"كبير","price":2.95}]'::jsonb),
  ('بيض سادة', NULL, 1, NULL, 'مناقيش', TRUE, '🍳', NULL),
  ('بيض مع جبنة', NULL, 1.25, NULL, 'مناقيش', TRUE, '🍳', NULL),
  ('بيض مع هوت دوغ', NULL, 1.25, NULL, 'مناقيش', TRUE, '🍳', NULL),
  ('بيض مع سجق', NULL, 1.25, NULL, 'مناقيش', TRUE, '🍳', NULL),
  ('بيض مع بسطرمة', NULL, 1.25, NULL, 'مناقيش', TRUE, '🍳', NULL),
  ('بيض مع سلامي', NULL, 1.25, NULL, 'مناقيش', TRUE, '🍳', NULL),
  ('بيض مع تيركي', NULL, 1.25, NULL, 'مناقيش', TRUE, '🍳', NULL),
  ('زعتر مع جبنة', NULL, 1.15, NULL, 'مناقيش', TRUE, '🌿', '[{"label":"عادي","price":1.15},{"label":"كبير","price":1.85}]'::jsonb),
  ('محمرة مع جبنة', NULL, 1, NULL, 'مناقيش مميزة', TRUE, '🌶️', '[{"label":"عادي","price":1},{"label":"كبير","price":2.5}]'::jsonb),
  ('شيش طاووق', NULL, 1.35, NULL, 'مناقيش مميزة', TRUE, '🍢', '[{"label":"عادي","price":1.35},{"label":"كبير","price":2.5}]'::jsonb),
  ('شيش مدخن', NULL, 1.35, NULL, 'مناقيش مميزة', TRUE, '🍢', '[{"label":"عادي","price":1.35},{"label":"كبير","price":2.5}]'::jsonb),
  ('دجاج باربيكيو', NULL, 1.35, NULL, 'مناقيش مميزة', TRUE, '🍗', '[{"label":"عادي","price":1.35},{"label":"كبير","price":2.5}]'::jsonb),
  ('دجاج باربيكيو مدخن', NULL, 1.35, NULL, 'مناقيش مميزة', TRUE, '🍗', '[{"label":"عادي","price":1.35},{"label":"كبير","price":2.5}]'::jsonb),
  ('تشيز ستيك', NULL, 1.35, NULL, 'مناقيش مميزة', TRUE, '🥩', '[{"label":"عادي","price":1.35},{"label":"كبير","price":2.5}]'::jsonb),
  ('لحمة بلدي بعجين', NULL, 1.35, NULL, 'مناقيش مميزة', TRUE, '🥩', '[{"label":"عادي","price":1.35},{"label":"كبير","price":2.5}]'::jsonb),
  ('عش البلبل', NULL, 1.35, NULL, 'مناقيش مميزة', TRUE, '🪺', '[{"label":"عادي","price":1.35},{"label":"كبير","price":2.5}]'::jsonb),
  ('لحمة بلدي بعجين مع جبنة', NULL, 1.5, NULL, 'مناقيش مميزة', TRUE, '🥩', '[{"label":"عادي","price":1.5},{"label":"كبير","price":2.5}]'::jsonb),
  ('زعتر مع خضار رول', NULL, 1.25, NULL, 'رولات', TRUE, '🌿', NULL),
  ('زعتر مع جبنة وخضار رول', NULL, 1.5, NULL, 'رولات', TRUE, '🌿', NULL),
  ('جبنة بيضاء مع خضار رول', NULL, 1.75, NULL, 'رولات', TRUE, '🧀', NULL),
  ('لبنة مع خضار رول', NULL, 1.75, NULL, 'رولات', TRUE, '🫙', NULL),
  ('لبنة مع زعتر وخضار رول', NULL, 1.75, NULL, 'رولات', TRUE, '🫙', NULL),
  ('تيركي رول', NULL, 2, NULL, 'رولات', TRUE, '🦃', NULL),
  ('سلامي رول', NULL, 2, NULL, 'رولات', TRUE, '🍖', NULL),
  ('هوت دوغ رول', NULL, 2, NULL, 'رولات', TRUE, '🌭', NULL),
  ('جبنة حلوم رول', NULL, 2, NULL, 'رولات', TRUE, '🧀', NULL),
  ('بطاطا مقلية رول', NULL, 1.75, NULL, 'رولات', TRUE, '🥔', NULL),
  ('فاهيتا دجاج رول', NULL, 2.3, NULL, 'رولات مميزة', TRUE, '🍗', NULL),
  ('شيش طاووق رول', NULL, 2.3, NULL, 'رولات مميزة', TRUE, '🍢', NULL),
  ('شيش طاووق مدخن رول', NULL, 2.3, NULL, 'رولات مميزة', TRUE, '🍢', NULL),
  ('دجاج باربيكيو رول', NULL, 2.3, NULL, 'رولات مميزة', TRUE, '🍗', NULL),
  ('دجاج باربيكيو مدخن رول', NULL, 2.3, NULL, 'رولات مميزة', TRUE, '🍗', NULL),
  ('زنجر رول', NULL, 2.3, NULL, 'رولات مميزة', TRUE, '🌶️', NULL),
  ('دجاج مسحب رول', NULL, 2.3, NULL, 'رولات مميزة', TRUE, '🍗', NULL),
  ('تشيز ستيك رول', NULL, 2.3, NULL, 'رولات مميزة', TRUE, '🥩', NULL),
  ('ألفريدو رول', NULL, 2.3, NULL, 'رولات مميزة', TRUE, '🍗', NULL),
  ('منقوشة ونار رول', NULL, 2.3, NULL, 'رولات مميزة', TRUE, '🔥', NULL),
  ('بطاطا', NULL, 1, NULL, 'فطائر', TRUE, '🥔', NULL),
  ('بطاطا مع جبنة', NULL, 1.2, NULL, 'فطائر', TRUE, '🥔', NULL),
  ('بطاطا مع سبانخ', NULL, 1.2, NULL, 'فطائر', TRUE, '🥔', NULL),
  ('سبانخ مع جبنة', NULL, 1.4, NULL, 'فطائر', TRUE, '🌿', NULL),
  ('جبنة بيضاء مع زعتر أخضر', NULL, 1.5, NULL, 'فطائر', TRUE, '🧀', NULL),
  ('فاهيتا دجاج', NULL, 2.5, NULL, 'فطائر', TRUE, '🍗', NULL),
  ('فطيرة زنجر', NULL, 2.5, NULL, 'فطائر', TRUE, '🌶️', NULL),
  ('فطيرة ألفريدو', NULL, 2.5, NULL, 'فطائر', TRUE, '🍗', NULL),
  ('فطيرة دجاج مع جبنة سائلة', NULL, 2.5, NULL, 'فطائر', TRUE, '🍗', NULL),
  ('فطيرة دجاج باربيكيو', NULL, 2.5, NULL, 'فطائر', TRUE, '🍗', NULL),
  ('فطيرة زنجر مع الكريمة', NULL, 2.75, NULL, 'فطائر', TRUE, '🌶️', NULL),
  ('فطيرة دجاج بالكاري والجبنة', NULL, 2.75, NULL, 'فطائر', TRUE, '🍛', NULL),
  ('10 أجنحة دجاج WINGS', 'باربيكيو / بافيلو / chili & sweet / honey mustard', 5.5, NULL, 'مقبلات وإضافات', TRUE, '🍗', NULL),
  ('8 قطع دجاج مسحب BONELESS', 'باربيكيو / بافيلو / chili & sweet / honey mustard', 5.5, NULL, 'مقبلات وإضافات', TRUE, '🍗', NULL),
  ('صحن سلطة', NULL, 1.5, NULL, 'مقبلات وإضافات', TRUE, '🥗', NULL),
  ('صحن بطاطا', NULL, 1, NULL, 'مقبلات وإضافات', TRUE, '🍟', '[{"label":"وسط","price":1},{"label":"كبير","price":2}]'::jsonb),
  ('إضافة خضار', NULL, 0.25, NULL, 'مقبلات وإضافات', TRUE, '🥗', '[{"label":"وسط","price":0.25},{"label":"كبير","price":0.5}]'::jsonb),
  ('إضافة جبنة', NULL, 0.25, NULL, 'مقبلات وإضافات', TRUE, '🧀', '[{"label":"وسط","price":0.25},{"label":"كبير","price":0.5}]'::jsonb),
  ('إضافة لحوم', NULL, 0.25, NULL, 'مقبلات وإضافات', TRUE, '🥩', '[{"label":"وسط","price":0.25},{"label":"كبير","price":0.5}]'::jsonb),
  ('ميني نيوتيلا', NULL, 0.75, NULL, 'حلويات', TRUE, '🍫', NULL),
  ('لوتس ميني', NULL, 0.75, NULL, 'حلويات', TRUE, '🍪', NULL),
  ('عسل بالقشطة ميني', NULL, 0.85, NULL, 'حلويات', TRUE, '🍯', NULL),
  ('فطيرة اللوتس مع القشطة', NULL, 1.5, NULL, 'حلويات', TRUE, '🍪', NULL),
  ('فطيرة العسل مع القشطة', NULL, 1.5, NULL, 'حلويات', TRUE, '🍯', NULL),
  ('فطيرة نيوتيلا', NULL, 1.5, NULL, 'حلويات', TRUE, '🍫', NULL),
  ('فطيرة اللوتس', NULL, 1.5, NULL, 'حلويات', TRUE, '🍪', NULL),
  ('مشروبات غازية', NULL, 0.35, NULL, 'مشروبات', TRUE, '🥤', NULL),
  ('عصائر', NULL, 0.5, NULL, 'مشروبات', TRUE, '🧃', NULL),
  ('شاي مثلج', NULL, 0.5, NULL, 'مشروبات', TRUE, '🍵', NULL),
  ('لبن شنينة', NULL, 0.5, NULL, 'مشروبات', TRUE, '🥛', NULL),
  ('مياه معدنية', NULL, 0.3, NULL, 'مشروبات', TRUE, '💧', NULL)
ON CONFLICT (name, category) DO NOTHING;

-- Step 4: Verify
SELECT COUNT(*) AS total_products FROM products;
